short_name = "Rex"
name = "ReX Engine"
major = 0
minor = 1
patch = 0
status = "beta"
status_version = 0
module_config = ""
website = "https://redotengine.org"
docs = "latest"
godot_major = 4
godot_minor = 4
godot_patch = 0
godot_status = "dev"
