#!/usr/bin/env python
from misc.utility.scons_hints import *

import os
import platform

Import("env")

openssl_include_path = ""  # initialized.

try:
    if os.getenv("EM_VERSION") is not None:
        pass  # NO WEB NOT EVER
    elif os.path.exists("/usr/local/lib/android"):
        pass
    elif platform.system() == "Linux":
        openssl_include_path = "/usr/include/openssl"  # Generic location for Linux.
        env.Append(LIBS=["ssl", "crypto"])
    elif platform.system() == "OpenBSD":
        openssl_include_path = "/usr/include/openssl"  # Generic OpenBSD location
        env.Append(["ssl", "crypto"])
    elif platform.system() == "FreeBSD":
        openssl_include_path = "/usr/local/include/openssl"  # Generic FreeBSD location
    elif platform.system() == "Darwin":
        if "iPhone" in platform.platform() or "iPad" in platform.platform():
            pass  # No support for this atm?
        else:
            pass  # Temporary.
    elif platform.system() == "Windows":
        openssl_include_path = "C:/OpenSSL/include"  # Generic location for Windows?
        env.Append(IBS=["libssl.lib", "libcrypto.lib"])
    else:
        pass

    env.Append(CPPATH=[openssl_include_path])
    env.add_source_files(env.modules_sources, "*.cpp")  # Add all cpp files to the build
except ImportError:
    pass
